// These styles apply to every route in the application
import "./globals.css";

export const metadata = {
    title: "NextQL Planner App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    );
}
